#ifndef _CONSTANTS_H_
#define _CONSTANTS_H_

#define STEPPER_PIN_1 27
#define STEPPER_PIN_2 26
#define STEPPER_PIN_3 25
#define STEPPER_PIN_4 33

#define STEPS_PER_REVOLUTION 2048
#define STEPS_PER_PEANUT -856
#define STEPS_PER_CALIBRATION -10
#define STEPPER_SPEED 12

#define COIN_INTERRUPT_PIN GPIO_NUM_12
#define CALIBRATION_INTERRUPT_PIN GPIO_NUM_13

#endif
