#ifndef _CONSTANTS_H_
#define _CONSTANTS_H_

#define STEPPER_PIN_1 4
#define STEPPER_PIN_2 5
#define STEPPER_PIN_3 6
#define STEPPER_PIN_4 7

#define STEPS_PER_REVOLUTION 2048
#define STEPS_PER_PEANUT -428
#define STEPS_PER_CALIBRATION -10
#define STEPPER_SPEED 12

#define COIN_INTERRUPT_PIN 2
#define CALIBRATION_INTERRUPT_PIN 3

#endif
